---
name: links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check links
        uses: UCL-MIRSG/.github/actions/links@c3814a70ce74e9b35fb361c4eeda033882314320 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
