---
name: Manage issues on the projects board

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@2dd2b7d44bf2445214fc76272ae2d42925c43206 # v0
        with:
          app-id: ${{ secrets.APP_ID }}
          app-pem: ${{ secrets.APP_PEM }}
